version: '3'

tasks:
  proto:
    desc: "Генерирует proto файлы"
    cmds:
      - protoc --go_out=. --go-grpc_out=. api/proto/{{.SERVICE}}/{{.VERSION}}/*.proto
    vars:
      SERVICE: '{{.SERVICE}}'
      VERSION: '{{.VERSION}}'

  run:
    desc: "Быстрый запуск"
    cmds:
      - go run services/{{.SERVICE}}/cmd/main.go
    vars:
      SERVICE: '{{.SERVICE}}'
  
  tests:
    desc: "Запустить все тесты"
    cmds:
      - go test -v ./...

  test:
    desc: "Тест сервиса"
    cmds:
      - go test -v ./services/{{.SERVICE}}/...
    vars:
      SERVICE: '{{.SERVICE}}'

  run-all-win:
    desc: "Запустить все сервисы"
    cmds:
      - cmd /c start cmd /k "go run services/gateway/cmd/main.go"
      - cmd /c start cmd /k "go run services/auth/cmd/main.go"
      - cmd /c start cmd /k "go run services/user/cmd/main.go"