# Общие поля
env: "prod"
auth_addr: "localhost:50051"
user_addr: "localhost:50052"
ca_cert: "certs/ca/ca-cert.pem"

# Сервисы
gateway:
  addr: "localhost:8080"
  timeout_read: 5s
  timeout_write: 10s
  timeout_idle: 120s
  shutdown_timeout: 15s
  certs_client:
    cert: "certs/gateway/client-cert.pem"
    cert_key: "certs/gateway/client-key.pem"
  rate_limiter:
    redis_client:
      addr: "localhost:6379"
      password: ""
      db: 0
      poolsize: 10
    all:
      limits:
        /login: 100
        /register: 20
        /refresh: 200
        /logout: 100
      expires:
        /login: 1m
        /register: 1m
        /refresh: 1m
        /logout: 1m
    ip:
      limits:
        /login: 5
        /register: 3
        /refresh: 10
        /logout: 10
      expires:
        /login: 1m
        /register: 5m
        /refresh: 1m
        /logout: 1m
  gRPCAuthClient:
    retry_max_attempts: 3
    retry_initial_backoff: 0.1s
    retry_max_backoff: 1s
    retry_backoff_multiplier: 2.0
    keepalive_time: 10s
    keepalive_timeout: 1s
    keepalive_permit_without_stream: false
  gRPCUserClient:
    retry_max_attempts: 3
    retry_initial_backoff: 0.1s
    retry_max_backoff: 1s
    retry_backoff_multiplier: 2.0
    keepalive_time: 10s
    keepalive_timeout: 1s
    keepalive_permit_without_stream: false
  metrics:
    addr: ":9090"
    timeout_read: 5s
    timeout_write: 10s
    timeout_idle: 120s
    shutdown_timeout: 15s
  circuit_breakers:
    auth:
      name: "auth"
      maxrequests: 3
      interval: 60s
      timeout: 10s
      maxfailures: 5
    user:
      name: "user"
      maxrequests: 3
      interval: 60s
      timeout: 10s
      maxfailures: 5

auth:
  shutdown_timeout: 10s
  certs_server:
    cert: "certs/auth/server-cert.pem"
    cert_key: "certs/auth/server-key.pem"
  secret_key: "default-secret-key-min-32-chars-long!"
  access_ttl: 15m
  refresh_ttl: 168h
  grpc_max_recv_msg_size: 1048576 # 1 MB = 1024 * 1024
  grpc_max_send_msg_size: 1048576
  grpc_conn_timeout: 10s
  grpc_max_conn_idle: 5m
  grpc_keepalive_time: 1m
  grpc_keepalive_timeout: 20s
  redis_client:
    addr: "localhost:6379"
    password: ""
    db: 0
    poolsize: 10

user:
  shutdown_timeout: 10s
  certs_server:
    cert: "certs/user/server-cert.pem"
    cert_key: "certs/user/server-key.pem"
  certs_client:
    cert: "certs/user/client-cert.pem"
    cert_key: "certs/user/client-key.pem"
  grpc_max_recv_msg_size: 1048576 # 1 MB = 1024 * 1024
  grpc_max_send_msg_size: 1048576
  grpc_conn_timeout: 10s
  grpc_max_conn_idle: 5m
  grpc_keepalive_time: 1m
  grpc_keepalive_timeout: 20s
  gRPCAuthClient:
    retry_max_attempts: 3
    retry_initial_backoff: 0.1s
    retry_max_backoff: 1s
    retry_backoff_multiplier: 2.0
    keepalive_time: 10s
    keepalive_timeout: 1s
    keepalive_permit_without_stream: true
  postgres:
    addr: "localhost:5432"
    user: "restaurant"
    password: "restaurant"
    db: "users_db"
    ssl: "disable"
